# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-18 03:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmd', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ct_time', models.DateTimeField(auto_now_add=True)),
                ('cpu_num_info', models.IntegerField(verbose_name='CPU百分比')),
            ],
        ),
        migrations.CreateModel(
            name='CpuName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='CPU名称')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=32, verbose_name='主机名称')),
                ('ip_addr', models.GenericIPAddressField(unique=True)),
                ('port', models.IntegerField(default=22)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_type', models.SmallIntegerField(choices=[(0, 'ssh-password'), (1, 'ssh-key')])),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostUserBind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reposity.Host')),
                ('host_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reposity.HostUser')),
            ],
        ),
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='机房')),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('me_num', models.IntegerField(verbose_name='内存百分比')),
                ('Memory_time', models.DateTimeField(auto_now_add=True)),
                ('host_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reposity.Host')),
            ],
        ),
        migrations.CreateModel(
            name='SessionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reposity.Account')),
                ('host_user_bind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reposity.HostUserBind')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.SmallIntegerField(choices=[(0, 'cmd'), (1, 'file_transfer')])),
                ('content', models.TextField(verbose_name='任务内容')),
                ('timeout', models.IntegerField(default=50, verbose_name='任务超时')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reposity.Account')),
            ],
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField(default='init....')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.SmallIntegerField(choices=[(0, '成功'), (1, '失败'), (2, '超时'), (3, '初始化')])),
                ('host_user_bind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reposity.HostUserBind')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reposity.Task')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.CharField(max_length=128, unique=True)),
                ('expire', models.IntegerField(default=300, verbose_name='超时时间(s)')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reposity.Account')),
                ('host_user_bind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reposity.HostUserBind')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='hostuser',
            unique_together=set([('username', 'password')]),
        ),
        migrations.AddField(
            model_name='hostgroup',
            name='host_user_binds',
            field=models.ManyToManyField(to='reposity.HostUserBind'),
        ),
        migrations.AddField(
            model_name='host',
            name='idc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reposity.IDC'),
        ),
        migrations.AddField(
            model_name='cpuname',
            name='host_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reposity.Host'),
        ),
        migrations.AddField(
            model_name='cpu',
            name='cpu_title_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reposity.CpuName'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reposity.SessionLog'),
        ),
        migrations.AddField(
            model_name='account',
            name='host_groups',
            field=models.ManyToManyField(blank=True, to='reposity.HostGroup'),
        ),
        migrations.AddField(
            model_name='account',
            name='host_user_binds',
            field=models.ManyToManyField(blank=True, to='reposity.HostUserBind'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carry.User'),
        ),
        migrations.AlterUniqueTogether(
            name='tasklog',
            unique_together=set([('task', 'host_user_bind')]),
        ),
        migrations.AlterUniqueTogether(
            name='hostuserbind',
            unique_together=set([('host', 'host_user')]),
        ),
    ]
